# Stage 1
FROM node:current-alpine3.10 AS stage_build
WORKDIR /home/node/app/
COPY package*.json ./
#Bug with Angular and latest NPM so forcing downgrade
RUN npm install
COPY . .
RUN npm run build

FROM nginx:latest as prod_build
COPY --from=stage_build /home/node/app/dist/frontend/ /usr/share/nginx/html



