# Stage 1
FROM node:current-alpine3.10 AS base_build
WORKDIR /usr/src/app/frontend
COPY package*.json ./
RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install
EXPOSE 4201
CMD ["npm", "start"]


