version: '3'
services:
  nodejs-server:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    container_name: express-backend
    volumes:
      - ./backend:/home/node/app/backend
  angular-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports: 
      - "4200:4200"
    container_name: angular-frontend
    volumes:
      - ./frontend:/home/node/app/frontend
