version: '3'
services:
  #nodejs-server:
  #  build:
  #    context: ./backend
  #    dockerfile: Dockerfile-dev
  #  ports:
  #    - "3000:3000"
  #  container_name: node-backend
  #  volumes:
  #    - ./api:/usr/src/app/backend
  #    - /usr/src/app/backend/node_modules
  angular-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports: 
      - "4201:4201"
    container_name: testapp
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules 
